import './globals.css'
import '@mantine/core/styles.css';
import { MantineProvider, ColorSchemeScript } from "@mantine/core";


export const metadata = {
  title: 'Adam Marsh │ Brand Experience',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body style={{ backgroundColor: "#fce7e6" }}>
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  )
}
